name: agenda_daytoday_task_systems
description: "مشروع فلاتر جديد لإدارة المهام المنزلية."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.13.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true